### ISSUE TITLE
Forced status doesnt work between providers

### ISSUE THREAD

**Issue by jimaek** [octodns/octodns#1072]
Hey, we started running into a weird issue. The config worked correctly until it stopped without any changes on our side.

It started failing with this error:

```
2023-09-27T18:49:30  [14004[47](https://github.com/jsdelivr/dns-gslb/actions/runs/6330184150/job/17192014023#step:6:48)72931136] INFO  GCoreProvider[gcore] populate:   found 11 records, exists=True
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.11.5/x64/bin/octodns-sync", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/octodns/cmds/sync.py", line 57, in main
    manager.sync(
  File "/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/octodns/manager.py", line 694, in sync
    ps, d = future.result()
            ^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/concurrent/futures/_base.py", line 4[56](https://github.com/jsdelivr/dns-gslb/actions/runs/6330184150/job/17192014023#step:6:57), in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/octodns/manager.py", line 4[57](https://github.com/jsdelivr/dns-gslb/actions/runs/6330184150/job/17192014023#step:6:58), in _populate_and_plan
    plan = target.plan(zone, processors=processors)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.5/x[64](https://github.com/jsdelivr/dns-gslb/actions/runs/6330184150/job/17192014023#step:6:65)/lib/python3.11/site-packages/octodns/provider/base.py", line 239, in plan
    desired = self._process_desired_zone(desired)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/octodns_gcore/__init__.py", line [66](https://github.com/jsdelivr/dns-gslb/actions/runs/6330184150/job/17192014023#step:6:67)7, in _process_desired_zone
    return super()._process_desired_zone(desired)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/octodns/provider/base.py", line 78, in _process_desired_zone
    self.supports_warn_or_except(msg, fallback)
  File "/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/octodns/provider/base.py", line 219, in supports_warn_or_except
    raise SupportsException(f'{self.id}: {msg}')
octodns.provider.SupportsException: gcore: "status" flag used in pools cloudflare,fastly in cdn.testzone.io. is not supported
Error: Process completed with exit code 1.
```

config:

```
'cdn':
  # This is a dynamic record when used with providers that support it
  dynamic:
    # These are the pools of records that can be referenced and thus used by rules
    pools:
      cloudflare:
        values:
        - value: cdn.jsdelivr.net.cdn.cloudflare.net.
          status: up
      fastly:
        values:
        - value: jsdelivr.map.fastly.net.
          status: up
```

Apparently Gcore's module doesnt support the status flag anymore? The reason I didn't open the issue in that repo is because I dont see any relevant updates in that module, which made me think the issue is a main Octodns release.

Our probem is that we need that parameter, without it NS1 tries to create monitors for failover which we dont need. But with it Gcore fails.

Any ideas what happened?

**Comment by jimaek** [comment]
Looks like octodns==0.9.21 works great, so its indeed not the module itself but the v1 upgrade :)

**Comment by ross** [comment]
See https://github.com/octodns/octodns#strict_supports and/or the CHANGELOG for the 1.x series https://github.com/octodns/octodns/blob/main/CHANGELOG.md#noteworthy-changes-2. Things that were previously warnings are now errors. There are ways to quell them if you don't want to or can't fix the underlying issue.

**Comment by jimaek** [comment]
Indeed, you're right. But is this the best course of action in this specific case? 
Since octodns is meant to manage multiple DNS providers, a standard parameter like "status" should not break anything even with strict=on. I would expect it to just work and apply to the providers that support it and be ignored by those that dont.

In our case I enabled strict=off, thanks for the quick response!

**Comment by ross** [comment]
> Since octodns is meant to manage multiple DNS providers, a standard parameter like "status" should not break anything even with strict=on.

Before it was just warning you that one or more of your providers couldn't do what you asked of it. There were quite a few cases where people weren't seeing the warnings, especially when new ones would crop up after they initially set things up. The switch to having strict on by default was in order to make it "safer" so that people would be sure to see and acknowledge the problems rather than it coming back to bite them.

**Comment by jimaek** [comment]
Maybe then it would make sense to add "status=off"?

Basically I don't want to use this feature at all, but NS1 by default will create monitors, and the only way to disable that is to set status=up, which in turn breaks Gcore, so now I also need to set strict=off, all to just bypass that little option :)

**Comment by ross** [comment]
I'm not super familiar with gcore's dynamic implementation or the provider's functionality. Ideally it'd support the concept of `status=up`.  If that's not possible `strict_supports=False` probably is the best option.
