### ISSUE TITLE
"dns.exception.SyntaxError: string too long" when updating DKIM TXT record

### ISSUE THREAD

**Issue by paulgear** [octodns/octodns#1088]
It appears that octodns-bind doesn't chunk long lines when attempting to update records.  Following is a lightly-edited excerpt of one attempt:

```
$ octodns-sync --config-file config/main.yml --doit --force
2023-05-01T19:27:06  [140206852075520] INFO  Manager __init__: config_file=config/main.yml (octoDNS 0.9.21)
2023-05-01T19:27:06  [140206852075520] INFO  Manager _config_executor: max_workers=2
2023-05-01T19:27:06  [140206852075520] INFO  Manager _config_include_meta: include_meta=False
2023-05-01T19:27:06  [140206852075520] INFO  Manager __init__: global_processors=[]
2023-05-01T19:27:06  [140206852075520] INFO  Manager __init__: provider=cloudflare (octodns_cloudflare 0.0.2)
2023-05-01T19:27:06  [140206852075520] INFO  Manager __init__: provider=digitalocean (octodns_digitalocean 0.0.2)
2023-05-01T19:27:06  [140206852075520] INFO  Manager __init__: provider=publicdns (octodns_bind 0.0.1)
2023-05-01T19:27:06  [140206852075520] INFO  Manager __init__: provider=writeyaml (octodns.provider.yaml 0.9.21)
2023-05-01T19:27:06  [140206852075520] INFO  Manager __init__: provider=yaml (octodns.provider.yaml 0.9.21)
2023-05-01T19:27:06  [140206852075520] INFO  Manager __init__: provider=zonefile (octodns_bind 0.0.1)
2023-05-01T19:27:06  [140206852075520] INFO  Manager sync: eligible_zones=[], eligible_targets=[], dry_run=False, force=True, plan_output_fh=<stdout>
2023-05-01T19:27:06  [140206852075520] INFO  Manager sync:   zone=gear.email.
2023-05-01T19:27:06  [140206852075520] INFO  Manager sync:   sources=['yaml'] -> targets=['digitalocean', 'publicdns']
2023-05-01T19:27:06  [140206818149952] INFO  YamlProvider[yaml] populate:   found 9 records, exists=False
2023-05-01T19:27:06  [140206818149952] INFO  DigitalOceanProvider[digitalocean] plan: desired=gear.email.
2023-05-01T19:27:07  [140206818149952] WARNING DigitalOceanProvider[digitalocean] populate: skipping unsupported SOA record
2023-05-01T19:27:07  [140206818149952] INFO  DigitalOceanProvider[digitalocean] populate:   found 9 records, exists=True
2023-05-01T19:27:07  [140206818149952] INFO  DigitalOceanProvider[digitalocean] plan:   No changes
2023-05-01T19:27:07  [140206818149952] INFO  Rfc2136Provider[publicdns] plan: desired=gear.email.
2023-05-01T19:27:07  [140206818149952] INFO  Rfc2136Provider[publicdns] populate:   found 9 records
2023-05-01T19:27:07  [140206818149952] INFO  Rfc2136Provider[publicdns] plan:   Creates=0, Updates=9, Deletes=0, Existing Records=9
2023-05-01T19:27:07  [140206852075520] INFO  Plan 
********************************************************************************
* gear.email.
********************************************************************************
* publicdns (Rfc2136Provider)
...
*   Update
*     <TxtRecord TXT 3600, 2018._domainkey.gear.email., ['v=DKIM1\; h=sha256\; k=rsa\; p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAx78E7PtJvr8vpoNgHdIAe+llFKoy8WuTXDd6Z5mm3D4AUva9MBt5fFetxg/kcRy3KMDnMw6kDybwbpS/oPw1ylk6DL1xit7Cr5xeYYSWKukxXURAlHwT2K72oUsFKRUvN1X9lVysAeo+H8H/22Z9fJ0P30sOuRIRqCaiz+OiUYicxy4xrpfH2s9a+o3yRwX3zhlp8GjRmmmyK5mf7CkQTCfjnKVsYtB7mabXXmClH9tlcymnBMoN9PeXxaS5JRRysVV8RBCC9/wmfp9y//cck8nvE/MavFpSUHvv+TfTTdVKDlsXPjKX8iZQv0nO3xhspgkqFquKjydiR8nf4meHhwIDAQAB']> ->
*     <TxtRecord TXT 36000, 2018._domainkey.gear.email., ['v=DKIM1\; h=sha256\; k=rsa\; p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAx78E7PtJvr8vpoNgHdIAe+llFKoy8WuTXDd6Z5mm3D4AUva9MBt5fFetxg/kcRy3KMDnMw6kDybwbpS/oPw1ylk6DL1xit7Cr5xeYYSWKukxXURAlHwT2K72oUsFKRUvN1X9lVysAeo+H8H/22Z9fJ0P30sOuRIRqCaiz+OiUYicxy4xrpfH2s9a+o3yRwX3zhlp8GjRmmmyK5mf7CkQTCfjnKVsYtB7mabXXmClH9tlcymnBMoN9PeXxaS5JRRysVV8RBCC9/wmfp9y//cck8nvE/MavFpSUHvv+TfTTdVKDlsXPjKX8iZQv0nO3xhspgkqFquKjydiR8nf4meHhwIDAQAB']> (yaml)
...
*   Summary: Creates=0, Updates=9, Deletes=0, Existing Records=9
********************************************************************************


2023-05-01T19:27:07  [140206852075520] INFO  Rfc2136Provider[publicdns] apply: making 9 changes to gear.email.
Traceback (most recent call last):
  File "/home/paulgear/.local/bin/octodns-sync", line 8, in <module>
    sys.exit(main())
  File "/home/paulgear/.local/lib/python3.10/site-packages/octodns/cmds/sync.py", line 57, in main
    manager.sync(
  File "/home/paulgear/.local/lib/python3.10/site-packages/octodns/manager.py", line 653, in sync
    total_changes += target.apply(plan)
  File "/home/paulgear/.local/lib/python3.10/site-packages/octodns/provider/base.py", line 245, in apply
    self._apply(plan)
  File "/home/paulgear/.local/lib/python3.10/site-packages/octodns_bind/__init__.py", line 215, in _apply
    update.replace(name, ttl, _type, *rdatas)
  File "/home/paulgear/.local/lib/python3.10/site-packages/dns/update.py", line 262, in replace
    self._add(True, self.update, name, *args)
  File "/home/paulgear/.local/lib/python3.10/site-packages/dns/update.py", line 168, in _add
    rd = dns.rdata.from_text(self.zone_rdclass, rdtype, s, self.origin)
  File "/home/paulgear/.local/lib/python3.10/site-packages/dns/rdata.py", line 767, in from_text
    rdata = cls.from_text(
  File "/home/paulgear/.local/lib/python3.10/site-packages/dns/rdtypes/txtbase.py", line 89, in from_text
    raise dns.exception.SyntaxError("string too long")
dns.exception.SyntaxError: string too long
```

**Comment by istr** [comment]
> for route53 and dyn provider it was solved in that way: https://github.com/octodns/octodns/pull/115/commits

For other providers (notably constellix) this does not work (yet), because they omit the space between the inner `""`.
So the
```python
ret.append(v.replace('" "', ''))
```
does not work for every provider.
Happy to have you here, @binlan, by the way. :wave:
