### ISSUE TITLE
Domain duplication [route53 -> bind9]

### ISSUE THREAD

**Issue by paxlo** [octodns/octodns#1164]
Hi @ross. I am using the configuration from my [previous ticket](https://github.com/octodns/octodns/issues/1146) to synchronise a large number of records from route53 to bind9. The latest version of octodns 1.6.1 is installed from pip. The records synchronised successfully, but many of them contain a duplicated domain like example.com.example.com.

```
$ORIGIN .
$TTL 900        ; 15 minutes
example.internal     IN SOA  ns-5.example.internal. hostmaster.example.internal. (
                                4          ; serial
                                604800     ; refresh (1 week)
                                86400      ; retry (1 day)
                                2419200    ; expire (4 weeks)
                                604800     ; minimum (1 week)
                                )
$TTL 86400      ; 1 day
                        NS      ns-5.example.internal.
$ORIGIN example.internal.
$TTL 300        ; 5 minutes
api                     CNAME   k8s-kaasingr-ingressn-5849e410fe-f568f9ed4e6a7d81.elb.us-east-1.amazonaws.com
argocd                  CNAME   k8s-kaasingr-ingressn-b0b7ae0801-03420a89ebc14a6b.elb.us-east-1.amazonaws.com
auth                    CNAME   k8s-kaasingr-ingressn-b0b7ae0801-03420a89ebc14a6b.elb.us-east-1.amazonaws.com
$ORIGIN dalaran.eks.aws.example.internal.
hubble                  CNAME   k8s-kaasingr-ingressn-1da6582ece-2ab191a55f9cee42.elb.us-east-1.amazonaws.com.example.internal.
jaeger                  CNAME   k8s-kaasingr-ingressn-1da6582ece-2ab191a55f9cee42.elb.us-east-1.amazonaws.com.example.internal.
kiali                   CNAME   k8s-kaasingr-ingressn-1da6582ece-2ab191a55f9cee42.elb.us-east-1.amazonaws.com.example.internal.
policy-reporter         CNAME   k8s-kaasingr-ingressn-1da6582ece-2ab191a55f9cee42.elb.us-east-1.amazonaws.com.example.internal.
prometheus              CNAME   k8s-kaasingr-ingressn-1da6582ece-2ab191a55f9cee42.elb.us-east-1.amazonaws.com.example.internal.
$ORIGIN eks.aws.example.internal.
$TTL 60 ; 1 minute
karazhan                CNAME   k8s-kaasingr-ingressn-5849e410fe-f568f9ed4e6a7d81.elb.us-east-1.amazonaws.com.example.internal.
$ORIGIN karazhan.eks.aws.example.internal.
$TTL 300        ; 5 minutes
hubble                  CNAME   karazhan.eks.aws.example.internal.example.internal.
jaeger                  CNAME   karazhan.eks.aws.example.internal.example.internal.
kiali                   CNAME   karazhan.eks.aws.example.internal.example.internal.
policy-reporter         CNAME   k8s-kaasingr-ingressn-5849e410fe-f568f9ed4e6a7d81.elb.us-east-1.amazonaws.com.example.internal.
prometheus              CNAME   k8s-kaasingr-ingressn-5849e410fe-f568f9ed4e6a7d81.elb.us-east-1.amazonaws.com.example.internal.
$ORIGIN naxxramas.eks.aws.example.internal.
hubble                  CNAME   k8s-kaasingr-ingressn-b0b7ae0801-03420a89ebc14a6b.elb.us-east-1.amazonaws.com.example.internal.
prometheus              CNAME   k8s-kaasingr-ingressn-b0b7ae0801-03420a89ebc14a6b.elb.us-east-1.amazonaws.com.example.internal.
$ORIGIN nordrassil.eks.aws.example.internal.
hubble                  CNAME   k8s-kaasingr-ingressn-35e532eba5-d5bb32dfef565330.elb.us-east-1.amazonaws.com.example.internal.
jaeger                  CNAME   k8s-kaasingr-ingressn-35e532eba5-d5bb32dfef565330.elb.us-east-1.amazonaws.com.example.internal.
kiali                   CNAME   k8s-kaasingr-ingressn-35e532eba5-d5bb32dfef565330.elb.us-east-1.amazonaws.com.example.internal.
kubeflow                CNAME   k8s-kaasingr-ingressn-35e532eba5-d5bb32dfef565330.elb.us-east-1.amazonaws.com.example.internal.
policy-reporter         CNAME   k8s-kaasingr-ingressn-35e532eba5-d5bb32dfef565330.elb.us-east-1.amazonaws.com.example.internal.
$ORIGIN eks.aws.example.internal.
hubble.test-istio       CNAME   test-istio.eks.aws.example.internal.example.internal.
$ORIGIN ulduar.eks.aws.example.internal.
hubble                  CNAME   ulduar.eks.aws.example.internal.example.internal.
prometheus              CNAME   k8s-kaasingr-ingressn-d4732f4733-d4ccb82e7bc9c6ac.elb.us-east-1.amazonaws.com.example.internal.
$ORIGIN infra.aws.example.internal.
_vmetrics._tcp          SRV     1 1 8428 vmetrics-1.infra.aws.example.internal.example.internal.
                        SRV     1 1 8428 vmetrics-2.infra.aws.example.internal.example.internal.
broker-1                A       10.60.5.87
broker-2                A       10.60.7.222
broker-3                A       10.60.6.27
controller-1            A       10.60.1.160
controller-2            A       10.60.1.118
controller-3            A       10.60.6.131
postgresql              CNAME   postgresql-infra.cqveovnuypi5.us-east-1.rds.amazonaws.com.example.internal.
vmetrics-1              A       10.60.3.52
vmetrics-2              A       10.60.1.72
$ORIGIN aws.example.internal.
kibana                  CNAME   k8s-kaasingr-ingressn-5849e410fe-f568f9ed4e6a7d81.elb.us-east-1.amazonaws.com.example.internal.
metrics                 CNAME   monitoring-1.aws.example.internal.example.internal.
monitoring              CNAME   monitoring-1.aws.example.internal.example.internal.
monitoring-1            A       10.60.7.175
vector                  CNAME   balancer-1.vector.aws.example.internal.example.internal.
$ORIGIN _tcp.vector.aws.example.internal.
_vector-gelf            SRV     1 1 10004 vector-1.vector.aws.example.internal.example.internal.
                        SRV     1 1 10004 vector-2.vector.aws.example.internal.example.internal.
_vector-parsing         SRV     1 1 10001 vector-1.vector.aws.example.internal.example.internal.
                        SRV     1 1 10001 vector-2.vector.aws.example.internal.example.internal.
_vector-passthrough     SRV     1 1 10000 vector-1.vector.aws.example.internal.example.internal.
                        SRV     1 1 10000 vector-2.vector.aws.example.internal.example.internal.
_vector-raw             SRV     1 1 10003 vector-1.vector.aws.example.internal.example.internal.
                        SRV     1 1 10003 vector-2.vector.aws.example.internal.example.internal.
```

Also, the EnsureTrailingDots processor is not working. If I add it, I get an error:
```
*   Summary: Creates=0, Updates=282, Deletes=0, Existing Records=455
********************************************************************************


2024-04-25T13:40:34  [140273318116224] INFO  Rfc2136Provider[rfc2136] apply: making 282 changes to example.internal.
Traceback (most recent call last):
  File "/opt/octodns/env/bin/octodns-sync", line 8, in <module>
282
    sys.exit(main())
             ^^^^^^
  File "/opt/octodns/env/lib/python3.12/site-packages/octodns/cmds/sync.py", line 62, in main
    manager.sync(
  File "/opt/octodns/env/lib/python3.12/site-packages/octodns/manager.py", line 857, in sync
    total_changes += target.apply(plan)
                     ^^^^^^^^^^^^^^^^^^
  File "/opt/octodns/env/lib/python3.12/site-packages/octodns/provider/base.py", line 298, in apply
    self._apply(plan)
  File "/opt/octodns/env/lib/python3.12/site-packages/octodns_bind/__init__.py", line 475, in _apply
    name, ttl, _type, rdatas = record.rrs
                               ^^^^^^^^^^
  File "/opt/octodns/env/lib/python3.12/site-packages/octodns/record/base.py", line 396, in rrs
    return self.fqdn, self.ttl, self._type, [self.value.rdata_text]
                                             ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'rdata_text'
```

Octo config:
```
providers:
  route53:
    class: octodns_route53.Route53Provider
    access_key_id: ACCESS_KEY_ID
    secret_access_key: SECRET_ACCESS_KEY
  rfc2136:
    class: octodns_bind.Rfc2136Provider
    host: 10.109.0.4
    ipv6: False
    key_name: 'rndc-key'
    key_algorithm: 'HMAC-MD5.SIG-ALG.REG.INT'
    key_secret: BIND_SECRET
processors:
  trailing-dots:
    class: octodns.processor.trailing_dots.EnsureTrailingDots
  no-root-ns:
    class: octodns.processor.filter.IgnoreRootNsFilter
  exclude-root-ns-changes:
    class: octodns.processor.filter.ExcludeRootNsChanges
    error: false
  not-these-types:
    class: octodns.processor.filter.TypeRejectlistFilter
    rejectlist:
      - NS
      - SOA
      - MX
    include_target: True
  only-these-types:
    class: octodns.processor.filter.TypeAllowlistFilter
    allowlist:
      - A
      - CNAME
      - SRV
    include_target: True
  not-these-names:
    class: octodns.processor.filter.NameRejectlistFilter
    rejectlist:
        - ns-5
zones:
  example.internal.:
    lenient: True
    sources:
      - route53
    processors:
      # - trailing-dots
      - no-root-ns
      - exclude-root-ns-changes
      - not-these-types
      - only-these-types
      - not-these-names
    targets:
      - rfc2136
```

**Comment by ross** [comment]
> Also, the EnsureTrailingDots processor is not working. If I add it, I get an error:

I believe this should address the double fqdns as discused in the previous issue https://github.com/octodns/octodns/issues/1146, so the problem here is that it's throwing the error.

I'll have to see if I can reproduce the problem. To that end if you're up for enabling the processor and opening up the file where the exception is happening, `/opt/octodns/env/lib/python3.12/site-packages/octodns/record/base.py` and adding the following just above line 396:

```python
from pprint import pprint
pprint({
    'self': self,
    'data': self.data,
})
```

That should give a jump start on reproducing the issue.

**Comment by ross** [comment]
Figured out what's happening here. The EnsureTrailingDots processor is changing the value type from a `CnameValue` to a `str` which doesn't have the right functionality. Exploring a fix.
