### ISSUE TITLE
octodns-dump fails with `KeyError: u'TTL'`

### ISSUE THREAD

**Issue by thepatrick** [octodns/octodns#232]
Trying to do an initial import and I get:

```
2018-04-13T16:04:51  [140682505373440] INFO  Manager __init__: config_file=./config/production.yaml
2018-04-13T16:04:51  [140682505373440] INFO  Manager __init__:   max_workers=1
2018-04-13T16:04:51  [140682505373440] INFO  Manager __init__:   max_workers=False
2018-04-13T16:04:51  [140682505373440] INFO  Manager dump: zone=tokbox.com., sources=()
Traceback (most recent call last):
  File "/home/pqg/Tokbox/devops/dns/env/bin/octodns-dump", line 11, in <module>
    sys.exit(main())
  File "/home/pqg/Tokbox/devops/dns/env/local/lib/python2.7/site-packages/octodns/cmds/dump.py", line 31, in main
    manager.dump(args.zone, args.output_dir, args.lenient, *args.source)
  File "/home/pqg/Tokbox/devops/dns/env/local/lib/python2.7/site-packages/octodns/manager.py", line 360, in dump
    source.populate(zone, lenient=lenient)
  File "/home/pqg/Tokbox/devops/dns/env/local/lib/python2.7/site-packages/octodns/provider/route53.py", line 472, in populate
    data = getattr(self, '_data_for_{}'.format(record_type))(rrset)
  File "/home/pqg/Tokbox/devops/dns/env/local/lib/python2.7/site-packages/octodns/provider/route53.py", line 315, in _data_for_geo
    'ttl': int(rrset['TTL'])
KeyError: u'TTL'
```

**Comment by ross** [comment]
If you don't mind can you add the following lines up above the line the `KeyError` is throwing, that'd be ~line 311 of /home/pqg/Tokbox/devops/dns/env/local/lib/python2.7/site-packages/octodns/provider/route53.py

```python
from pprint import pprint
pprint(rrset)
```

I haven't run across a situation where a Route53 record doesn't have a TTL and can't find a way to create one without a value so I'm curious of the details here, what type of record and what values etc.

**Comment by thepatrick** [comment]
Here's what I get:

```
{u'Name': 'tokbox.com.',
 u'ResourceRecords': [{u'Value': 'This resource record set includes an attribute that is unsupported on this Route 53 endpoint. Please consider using a newer endpoint or a tool that does so.'}],
 u'TrafficPolicyInstanceId': '...',
 u'Type': 'A'}
```

**Comment by ross** [comment]
Interesting. That's not something I've ever run across. Best search result for it is https://forums.aws.amazon.com/thread.jspa?threadID=63893, but that's pretty old. Coming back to your json I see `TrafficPolicyInstanceId` which leads me think the zone is using resource types that aren't supported/recognized by octoDNS. That functionality is documented in https://docs.aws.amazon.com/Route53/latest/APIReference/API_ResourceRecordSet.html. Since this is a pretty AWS-specific thing the reality is that it falls outside of the stuff that octoDNS is likely to support, at least in the near-term. For now we'd probably just make the provider handle and skip those types of records (with a warning.)
