### ISSUE TITLE
How can I limit the providers for a specific subzone

### ISSUE THREAD

**Issue by yfried** [octodns/octodns#499]
Hi,
I have a zone with 2 providers:
config.yaml:
```yaml
example.com.:
    sources:
      - config
    targets:
      - route53
      - azuredns
```
And:
example.com.yaml
```yaml
'':  
    - type: ALIAS
      ttl: 1
      value: www.example.com.
www:
    ttl: 1
    type: CNAME
    value: foo.bar.com.
test:
    ttl: 1
    type: CNAME
    value: foo2.bar.com.
subzone1:
    ttl: 1
    type: CNAME
    value: foo3.bar.com.
```

I'd like to limit a specific subzone in it to a single provider so I tried to add an entry for it:
```yaml
example.com.:
    sources:
      - config
    targets:
      - route53
      - azuredns
subzone1.example.com.:
    sources:
      - config
    targets:
      - route53
```

However, validation fails with:
```
Traceback (most recent call last):
  File "/Users/yairfr/.virtualenvs/octodns/bin/octodns-validate", line 8, in <module>
    sys.exit(main())
  File "/Users/yairfr/.virtualenvs/octodns/lib/python2.7/site-packages/octodns/cmds/validate.py", line 24, in main
    manager.validate_configs()
  File "/Users/yairfr/.virtualenvs/octodns/lib/python2.7/site-packages/octodns/manager.py", line 427, in validate_configs
    source.populate(zone)
  File "/Users/yairfr/.virtualenvs/octodns/lib/python2.7/site-packages/octodns/provider/yaml.py", line 77, in populate
    self._populate_from_file(filename, zone, lenient)
  File "/Users/yairfr/.virtualenvs/octodns/lib/python2.7/site-packages/octodns/provider/yaml.py", line 62, in _populate_from_file
    zone.add_record(record, lenient=lenient)
  File "/Users/yairfr/.virtualenvs/octodns/lib/python2.7/site-packages/octodns/zone.py", line 75, in add_record
    .format(record.fqdn))
octodns.zone.SubzoneRecordException: Record subzone1.example.com. a managed sub-zone and not of type NS
```

how can I make this work?

**Comment by ross** [comment]
Once you split off the subzone, the `subzone1` `CNAME` in the parent needs to live in the subzone rather than the parent otherwise when you query `subzone1.example.com` the `route53` NS records would be found, the query sent to those NS and they wouldn't know know anything about that record/CNAME. 

Trying to summarize, once you have subzone1 split off things with that name have to go into the subzone otherwise they can't be looked up correctly.

There's also other DNS-spec things specific to `CNAME`s at play here. `CNAME`s can't live at the root of a zone, you'll have to use `ALIAS`, but unfortunately Route53 doesn't support them (it has it's own internal alias, but it's not a CNAME workalike.) `CNAME` also can't exist along side other record types, here that'd be the `NS`.
