### ISSUE TITLE
Error in Ns1Provider

### ISSUE THREAD

**Issue by vanbroup** [octodns/octodns#51]
When running 'octodns-sync' with '--doit' I get the error below with one of my zones. The command runs fine without pushing the changes.

This might be a bug in the NS1 SDK @weyrick?

```sh
2017-06-02T10:20:57  [139657304188672] INFO  Ns1Provider[nsone] apply: making changes
Traceback (most recent call last):
  File "/usr/local/bin/octodns-sync", line 11, in <module>
    load_entry_point('octodns==0.8.0', 'console_scripts', 'octodns-sync')()
  File "/usr/local/lib/python2.7/dist-packages/octodns/cmds/sync.py", line 39, in main
    dry_run=not args.doit, force=args.force)
  File "/usr/local/lib/python2.7/dist-packages/octodns/manager.py", line 282, in sync
    total_changes += target.apply(plan)
  File "/usr/local/lib/python2.7/dist-packages/octodns/provider/base.py", line 143, in apply
    self._apply(plan)
  File "/usr/local/lib/python2.7/dist-packages/octodns/provider/ns1.py", line 202, in _apply
    getattr(self, '_apply_{}'.format(class_name))(nsone_zone, change)
  File "/usr/local/lib/python2.7/dist-packages/octodns/provider/ns1.py", line 167, in _apply_Create
    getattr(nsone_zone, 'add_{}'.format(_type))(name, **params)
  File "/usr/local/lib/python2.7/dist-packages/nsone/zones.py", line 131, in add_X
    return record.create(callback=callback, errback=errback, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/nsone/records.py", line 130, in create
    callback=success, errback=errback, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/nsone/rest/records.py", line 113, in create
    **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/nsone/rest/records.py", line 124, in create_raw
    errback=errback)
  File "/usr/local/lib/python2.7/dist-packages/nsone/rest/resource.py", line 73, in _make_request
    return self._transport.send(type, self._make_url(path), **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/nsone/rest/transport/requests.py", line 48, in send
    resp.text)
  File "/usr/local/lib/python2.7/dist-packages/nsone/rest/errors.py", line 53, in __init__
    hdrs = response.headers._rawHeaders
AttributeError: 'CaseInsensitiveDict' object has no attribute '_rawHeaders'
```

It looks to be caused by an excessive number connections for a zone with many records. In the log below I replaced the zone name with example.com, all record names with 'somerecord' and removed a range of lines (from the original 110) for visibility.

```sh
2017-06-02T10:31:15  [140391072339712] DEBUG urllib3.connectionpool Starting new HTTPS connection (1): api.nsone.net
2017-06-02T10:31:15  [140391072339712] DEBUG urllib3.connectionpool https://api.nsone.net:443 "PUT /v1/zones/example.com/somerecord/A HTTP/1.1" 200 None
2017-06-02T10:31:15  [140391072339712] DEBUG urllib3.connectionpool Starting new HTTPS connection (1): api.nsone.net
2017-06-02T10:31:16  [140391072339712] DEBUG urllib3.connectionpool https://api.nsone.net:443 "PUT /v1/zones/example.com/somerecord/A HTTP/1.1" 200 None
2017-06-02T10:31:16  [140391072339712] DEBUG urllib3.connectionpool Starting new HTTPS connection (1): api.nsone.net
2017-06-02T10:31:16  [140391072339712] DEBUG urllib3.connectionpool https://api.nsone.net:443 "PUT /v1/zones/example.com/somerecord/A HTTP/1.1" 200 None
2017-06-02T10:31:16  [140391072339712] DEBUG urllib3.connectionpool Starting new HTTPS connection (1): api.nsone.net
2017-06-02T10:31:16  [140391072339712] DEBUG urllib3.connectionpool https://api.nsone.net:443 "PUT /v1/zones/example.com/somerecord/A HTTP/1.1" 200 None
2017-06-02T10:31:16  [140391072339712] DEBUG urllib3.connectionpool Starting new HTTPS connection (1): api.nsone.net
2017-06-02T10:31:17  [140391072339712] DEBUG urllib3.connectionpool https://api.nsone.net:443 "PUT /v1/zones/example.com/somerecord/A HTTP/1.1" 200 None
.........
2017-06-02T10:31:37  [140391072339712] DEBUG urllib3.connectionpool https://api.nsone.net:443 "PUT /v1/zones/example.com/somerecord/CNAME HTTP/1.1" 200 None
2017-06-02T10:31:38  [140391072339712] DEBUG urllib3.connectionpool Starting new HTTPS connection (1): api.nsone.net
2017-06-02T10:31:38  [140391072339712] DEBUG urllib3.connectionpool https://api.nsone.net:443 "PUT /v1/zones/example.com/somerecord/CNAME HTTP/1.1" 200 None
2017-06-02T10:31:38  [140391072339712] DEBUG urllib3.connectionpool Starting new HTTPS connection (1): api.nsone.net
2017-06-02T10:31:38  [140391072339712] DEBUG urllib3.connectionpool https://api.nsone.net:443 "PUT /v1/zones/example.com/somerecord/A HTTP/1.1" 429 34
```

**Comment by vanbroup** [comment]
While it doesn't look good that for every record a new connection is established, this does look to be a rate limiting problem with NS1. I can't say that requests are made really quickly so maybe @weyrick can have a look to see if they can be less aggressive.

See last line of the previous log:
`2017-06-02T10:31:38  [140391072339712] DEBUG urllib3.connectionpool https://api.nsone.net:443 "PUT /v1/zones/example.com/somerecord/A HTTP/1.1" 429 34`

@ross should we try to add a configuration option to providers to allow a pause between calls or something?

**Comment by ross** [comment]
> @ross should we try to add a configuration option to providers to allow a pause between calls or something?

If the client lib has issues I'd rather start there and see if we can work them out rather than including work-arounds in octoDNS. Definitely is odd that it's creating a new connection for every request, but as you point out the error may be unrelated. At the very least it looks like the client library may be eating/mis-handling the 429 error and covering it up with an exception it runs into when it tries to use the invalid 429. If it's using `requests` perhaps it's missing `raise_for_status` calls after each get/post.

If the client lib doesn't rate-limit automatically then that's probably worth looking at handling in `Ns1Provider`. I don't have any rate-limit handling in the other providers, but that may just be because I haven't managed to hit their rate limits. It may be best to look at building the rate-limiting code while having the actual problem if you want to take a swing at it. If I were to look at it I'd have to fake a 429 based on assumptions about how/when it's throwing the 429. 

I'm not sure it'd be possible to cleanly handle the rate limiting if the client lib is eating the actual error so that's probably the place to start.

**Comment by fcelda** [comment]
Hey. This is Jan from NS1. Yes, our library really misbehaves with 429 status code. We are gonna fix it. But as for the rate limiting, I think it needs to be handled in Octodns.

**Comment by vanbroup** [comment]
Hi @fcelda, thanks for confirming the problem. I think it's worth and best to solve this problem in the NS1 SDK, moving the problem to OctoDNS would probably result in a simple pause after every request and thus unnecessary delays.

The NS1 API is returning "X-RateLimit-Remaining" header which could be used to hold of new requests. You can probably record that in the established session (as you don't want to reconnect for every request) and pause the request for "X-RateLimit-Period" / "X-RateLimit-Limit" when remaining is 0. 

A simple implementation would be to retry after a pause (potentially with a backoff) when you get a 429. If you don't want this by default it could be a configuration option for the SDK?

You could also implement the standard HTTP "Retry-After" header in the NS1 API, this way the server has more control over the backoff policy after hitting the rate limiting.

**Comment by fcelda** [comment]
Good point. I suggested to handle this in Octodns because creating a blocking calls in SDK might not be desired by all users. But we will definitely take a look at the options and see what can be done.

Ad Retry-After, that can be added for sure. I will create an internal ticket for that right away.

Thanks for the comments!

**Comment by ross** [comment]
@fcelda Any updates on the client library fix? Doing a bug scrub as I have some time this week to spend on things and wanted to see if there's progress here so I know whether this is ready to put on the todo list or not.

**Comment by pashap** [comment]
@ross sorry for the delay, i let this one slip. im at NS1 as well, and told @fcelda id take care of the poor header handling thats causing the exception a couple of weeks ago. 

i just created a [PR](https://github.com/ns1/nsone-python/pull/30) that should fix header handling in the ns1 python sdk.

**Comment by ross** [comment]
Thanks @pashap I'll take a look at getting things updated, if I'm lucky this week.

**Comment by vanbroup** [comment]
Hi @pashap, can you also have a look at the not used connection pool as listed in this issue?

**Comment by weyrick** [comment]
@vanbroup can you paste your config so we can better understand why it's making so many connections so quickly? We're thinking there is some efficiency because there should be no reason to make e.g. 5+ PUT calls to the exact same record within 2s, as your log shows.

Re: connection pooling - even if enabled, this would not circumvent rate limiting, so we need to track down the root problem here.

Thanks!

**Comment by vanbroup** [comment]
@weyrick the specific zone has hundreds of records and the zone in NS1 provider is empty to start with, updates might involve quite a few records so rate-limiting needs to be handled.

```
---
providers:
  config:
    class: octodns.provider.yaml.YamlProvider
    directory: ./testzones
  cloudflare:
    class: octodns.provider.cloudflare.CloudflareProvider
    email: env/DNS_CF_EMAIL
    token: env/DNS_CF_TOKEN
  dyn:
    class: octodns.provider.dyn.DynProvider
    customer: env/DNS_DYN_CUST
    username: env/DNS_DYN_USER
    password: env/DNS_DYN_PASS
    traffic_directors_enabled: true
  nsone:
    class: octodns.provider.ns1.Ns1Provider
    api_key: env/DNS_NS1_API_KEY
  route53:
    class: octodns.provider.route53.Route53Provider
    access_key_id: env/DNS_R53_KEYID
    secret_access_key: env/DNS_R53_SECRET
zones:
  example.com.:
    sources:
      - config
    targets:
      - route53
      - nsone
      - dyn
```

A zone file with a lot of records: [example.com.yaml](https://github.com/github/octodns/files/1090876/zone.txt)

**Comment by weyrick** [comment]
@vanbroup thanks. So, agreed that the rate limiting needs to be addressed at some level. But, we're still confused at the output you pasted since it shows the _same_ record getting 5 separate HTTP PUT requests, which shouldn't be necessary. If there is a bug causing individual records to make more requests than it should, that will clearly exacerbate the rate limit problem so we just wanted to dig into that issue specifically.

```
2017-06-02T10:31:15  [140391072339712] DEBUG urllib3.connectionpool Starting new HTTPS connection (1): api.nsone.net
2017-06-02T10:31:15  [140391072339712] DEBUG urllib3.connectionpool https://api.nsone.net:443 "PUT /v1/zones/example.com/somerecord/A HTTP/1.1" 200 None
2017-06-02T10:31:15  [140391072339712] DEBUG urllib3.connectionpool Starting new HTTPS connection (1): api.nsone.net
2017-06-02T10:31:16  [140391072339712] DEBUG urllib3.connectionpool https://api.nsone.net:443 "PUT /v1/zones/example.com/somerecord/A HTTP/1.1" 200 None
2017-06-02T10:31:16  [140391072339712] DEBUG urllib3.connectionpool Starting new HTTPS connection (1): api.nsone.net
2017-06-02T10:31:16  [140391072339712] DEBUG urllib3.connectionpool https://api.nsone.net:443 "PUT /v1/zones/example.com/somerecord/A HTTP/1.1" 200 None
2017-06-02T10:31:16  [140391072339712] DEBUG urllib3.connectionpool Starting new HTTPS connection (1): api.nsone.net
2017-06-02T10:31:16  [140391072339712] DEBUG urllib3.connectionpool https://api.nsone.net:443 "PUT /v1/zones/example.com/somerecord/A HTTP/1.1" 200 None
2017-06-02T10:31:16  [140391072339712] DEBUG urllib3.connectionpool Starting new HTTPS connection (1): api.nsone.net
2017-06-02T10:31:17  [140391072339712] DEBUG urllib3.connectionpool https://api.nsone.net:443 "PUT /v1/zones/example.com/somerecord/A HTTP/1.1" 200 None
```

**Comment by vanbroup** [comment]
Sorry, that is my reaction of the log file before posting online. If you run my example zone you will see the same behavior.

**Comment by weyrick** [comment]
Ok so I've verified that with latest nsone client change, the rate limit raises in a more reasonable fashion, and that it doesn't seem to be doing anything too inefficient during the sync:

```
2017-06-27T17:39:22  [140736046773184] DEBUG urllib3.connectionpool https://api.nsone.net:443 "PUT /v1/zones/sweyrickexample.com/record35.sweyrickexample.com/A HTTP/1.1" 200 None
2017-06-27T17:39:22  [140736046773184] DEBUG urllib3.connectionpool Starting new HTTPS connection (1): api.nsone.net
2017-06-27T17:39:22  [140736046773184] DEBUG urllib3.connectionpool https://api.nsone.net:443 "PUT /v1/zones/sweyrickexample.com/record42.sweyrickexample.com/A HTTP/1.1" 200 None
2017-06-27T17:39:22  [140736046773184] DEBUG urllib3.connectionpool Starting new HTTPS connection (1): api.nsone.net
2017-06-27T17:39:22  [140736046773184] DEBUG urllib3.connectionpool https://api.nsone.net:443 "PUT /v1/zones/sweyrickexample.com/record38.sweyrickexample.com/A HTTP/1.1" 429 34
Traceback (most recent call last):
  File "/Users/sweyrick/Virtualenvs/main/bin/octodns-sync", line 11, in <module>
    load_entry_point('octodns==0.8.0', 'console_scripts', 'octodns-sync')()
  File "build/bdist.macosx-10.12-x86_64/egg/octodns/cmds/sync.py", line 39, in main
  File "build/bdist.macosx-10.12-x86_64/egg/octodns/manager.py", line 308, in sync
  File "build/bdist.macosx-10.12-x86_64/egg/octodns/provider/base.py", line 143, in apply
  File "build/bdist.macosx-10.12-x86_64/egg/octodns/provider/ns1.py", line 209, in _apply
  File "build/bdist.macosx-10.12-x86_64/egg/octodns/provider/ns1.py", line 174, in _apply_Create
  File "/Users/sweyrick/Virtualenvs/main/lib/python2.7/site-packages/nsone/zones.py", line 131, in add_X
    return record.create(callback=callback, errback=errback, **kwargs)
  File "/Users/sweyrick/Virtualenvs/main/lib/python2.7/site-packages/nsone/records.py", line 130, in create
    callback=success, errback=errback, **kwargs)
  File "/Users/sweyrick/Virtualenvs/main/lib/python2.7/site-packages/nsone/rest/records.py", line 113, in create
    **kwargs)
  File "/Users/sweyrick/Virtualenvs/main/lib/python2.7/site-packages/nsone/rest/records.py", line 124, in create_raw
    errback=errback)
  File "/Users/sweyrick/Virtualenvs/main/lib/python2.7/site-packages/nsone/rest/resource.py", line 73, in _make_request
    return self._transport.send(type, self._make_url(path), **kwargs)
  File "/Users/sweyrick/Virtualenvs/main/lib/python2.7/site-packages/nsone/rest/transport/requests.py", line 51, in send
    remaining=resp.headers.get('X-RateLimit-Remaining', 100)
nsone.rest.errors.RateLimitException: rate limit exceeded: Rate limit exceeded
```

I agree it would be useful if either the nsone client or octo could catch that exception and use it to add a pause and try again automatically. We don't have the bandwidth to do this in house at the moment, but could provide assistance to anyone wants to contribute.

**Comment by ross** [comment]
> I agree it would be useful if either the nsone client or octo could catch that exception and use it to add a pause and try again automatically.

PR to add support is https://github.com/github/octodns/pull/81, don't know what to make the default value for the sleep before retry.

**Comment by ross** [comment]
@weyrick @vanbroup In looking into the details of the rate-limiting handling in https://github.com/github/octodns/pull/81 I noticed that the nsone's `RequestsTransport` [doesn't use a `Session`](https://github.com/ns1/nsone-python/blob/3f6b88a2e026ccc8c9249a99322691705e3be556/nsone/rest/transport/requests.py#L25-L30). My understanding of python requests is that a Session is required to use re-use connections (keep-alive) so that'd probably explain the behavior you were seeing with a new connection for every every request. I'm seeing the same thing in local testing once I turn on full debugging for octoDNS and python requests.

**Comment by weyrick** [comment]
Thanks, that looks like a good improvement, I'll get that on our python client roadmap. Note the rate limit will still be in effect, but it should burst up to the limit faster.
