### ISSUE TITLE
Dry run didn't catch improperly formatted MX record, broke with --doit

### ISSUE THREAD

**Issue by zachlatta** [octodns/octodns#600]
Hi there, we use OctoDNS to manage [Hack Club](https://hackclub.com)'s DNS records and it's amazing! It means we can open source all of our DNS records at [`hackclub/dns`](https://github.com/hackclub/dns). I love the idea of "infrastructure as code" and OctoDNS helps us a lot.

We recently ran into an issue where someone added an MX record with the `exchange` value `100 mx.sendgrid.net.`. We have a test suite that does a dry run, which didn't surface any issues with this value, but when it was ran with `--doit`, we got an ambiguous error.

I was able to figure out that we had to remove `100 ` from the record value, which fixed `--doit`. Setting `exchange` to just `mx.sendgrid.net.` worked fine, but as a user I would expect OctoDNS to surface this error during the dry run.

Here's the error log:

```
...(many lines above this)...
*   Create <MxRecord MX 1, front-mail.hackclub.com., [''1 100 mx.sendgrid.net.'']> (config)
*   Create <TxtRecord TXT 1, front-mail.hackclub.com., ['v=spf1 include:sendgrid.net ~all']> (config)
*   Summary: Creates=3, Updates=1, Deletes=0, Existing Records=184
********************************************************************************


2020-08-30T23:28:15  [140229093717632] INFO  DnsimpleProvider[dnsimple] apply: making changes
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/2.7.18/x64/bin/octodns-sync", line 11, in <module>
    load_entry_point('octodns==0.9.10', 'console_scripts', 'octodns-sync')()
  File "/opt/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/octodns/cmds/sync.py", line 39, in main
    dry_run=not args.doit, force=args.force)
  File "/opt/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/octodns/manager.py", line 344, in sync
    total_changes += target.apply(plan)
  File "/opt/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/octodns/provider/base.py", line 95, in apply
    self._apply(plan)
  File "/opt/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/octodns/provider/dnsimple.py", line 416, in _apply
    getattr(self, '_apply_{}'.format(class_name))(change)
  File "/opt/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/octodns/provider/dnsimple.py", line 387, in _apply_Create
    self._client.record_create(new.zone.name[:-1], params)
  File "/opt/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/octodns/provider/dnsimple.py", line 78, in record_create
```

And here's the commit in our repo that ran into this issue: https://github.com/hackclub/dns/commit/48ac4d122cf1bb426b7895ffa50d3ecd4ff7990d#diff-be3b615b181f7f7bf89114f9ef473a86R416

**Comment by ross** [comment]
Hi @zachlatta. There are some existing "validations" on MX records, https://github.com/github/octodns/blob/8e62bd9adad878563bef678fba06bc8e910c8fe4/octodns/record/__init__.py#L847-L871, but nothing that specifically look for that sort of case.

It could probably be caught by looking for spaces in the name and would likely apply equally well to a number of other types of values: `ALIAS`, `CNAME`, `SRV`.  Would welcome PRs w/tests to that effect. Otherwise this issue can track it as a TODO.

**Comment by ross** [comment]
Just filed https://github.com/octodns/octodns/pull/873 which should add the validation discussed here.
