### ISSUE TITLE
Support UltraDNS's Apex Alias records

### ISSUE THREAD

**Issue by nikolay-te** [octodns/octodns#644]
It seems that currently `octodns` does not support the Apex Alias records that one can configure on UltraDNS.
E.g. trying to dump a zone from UltraDNS with such records causes `octodns-dump` to crash:

```
octodns-dump --config-file ./config/staging.yaml --output-dir ./ stg.XXX.com. ultradns                                                                                                                   
2020-12-10T16:27:50  [4492312000] INFO  Manager __init__: config_file=./config/staging.yaml
2020-12-10T16:27:50  [4492312000] INFO  Manager __init__:   max_workers=2
2020-12-10T16:27:50  [4492312000] INFO  Manager __init__:   include_meta=False
2020-12-10T16:27:51  [4492312000] INFO  Manager dump: zone=stg.XXX.com., sources=()
Traceback (most recent call last):
  File "/Users/ndenev/te/octodns/venv/bin/octodns-dump", line 8, in <module>
    sys.exit(main())
  File "/Users/ndenev/te/octodns/venv/lib/python3.9/site-packages/octodns/cmds/dump.py", line 34, in main
    manager.dump(args.zone, args.output_dir, args.lenient, args.split,
  File "/Users/ndenev/te/octodns/venv/lib/python3.9/site-packages/octodns/manager.py", line 469, in dump
    source.populate(zone, lenient=lenient)
  File "/Users/ndenev/te/octodns/venv/lib/python3.9/site-packages/octodns/provider/ultra.py", line 290, in populate
    _type = self.RECORDS_TO_TYPE[record['rrtype']]
KeyError: 'APEXALIAS (65282)'
```

**Comment by ross** [comment]
Likely 2 things there:

1. The Ultra DNS provider should ignore types it/octoDNS doesn't understand/support
2. I suspect `APEXALIAS` can be mapped to octoDNS's `ALIAS` type, but I'm not familiar with Ultra DNS so can't say for sure.

/cc @phelpsw who wrote the provider

**Comment by nikolay-te** [comment]
I've opened https://github.com/octodns/octodns/pull/646 which should make it so records with unknown types are ignored and are also logged as warnings.

**Comment by sbrinkerhoff** [comment]
Reading through UltraDNS's API it appears they treat the `APEXALIAS` similarly to other providers `ALIAS` implementations.  Mapping their APEXALIAS to OctoDNS's ALIAS type allows sourcing from UltraDNS correctly.  To create/update (case 1) or delete (case 2) requires mutating the type from ALIAS to APEXALIAS for the REST API call to work correctly:

```
    def _gen_data(self, record):
        zone_name = self._remove_prefix(record.fqdn, record.name + '.')

        # UltraDNS treats the `APEXALIAS` type as the OctaDNS `ALIAS` 
        # recordtype.  This maintains compatabiltiy with other
        if record._type == "ALIAS":
            record_type = "APEXALIAS"
        else:
            record_type = record._type

        path = '/v2/zones/{}/rrsets/{}/{}'.format(zone_name,
                                                  record_type,
                                                  record.fqdn)
        contents_for = getattr(self, '_contents_for_{}'.format(record._type))
        return path, contents_for(record)
```

and

```
    def _apply_Delete(self, change):
        existing = change.existing

        for record in self.zone_records(existing.zone):
            if record['rrtype'] == 'SOA (6)':
                continue
            if existing.fqdn == record['ownerName'] and \
               existing._type == self.RECORDS_TO_TYPE[record['rrtype']]:
                zone_name = self._remove_prefix(existing.fqdn,
                                                existing.name + '.')

                if existing._type == "ALIAS":
                    existing._type = "APEXALIAS"

                path = '/v2/zones/{}/rrsets/{}/{}'.format(zone_name,
                                                          existing._type,
                                                          existing.fqdn)
                self._delete(path, json_response=False)
```

Is there a preferred way to handle this mutation?

**Comment by sbrinkerhoff** [comment]
I added #721 to add support for the Octodns `ALIAS` type which is mutated to an equivalent `APEXALIAS` REST URI when calling UltraDNS.

**Comment by sbrinkerhoff** [comment]
@ross When the next release is cut, the `README.md` should be updated to reference `ALIAS` support on `UltraDNS`.

**Comment by ross** [comment]
> @ross When the next release is cut, the `README.md` should be updated to reference `ALIAS` support on `UltraDNS`.

Feel free to PR the edit now. If I'd thought of it we would have done it in the PR that added support.
