### ISSUE TITLE
AzureProvider fails to plan when zone doesn't exist

### ISSUE THREAD

**Issue by ross** [octodns/octodns#655]
```
2020-12-29T01:54:18  [139903669815104] INFO  AzureProvider[azure] plan: desired=blahblah.com.
Traceback (most recent call last):
  File "/usr/local/bin/octodns-sync", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/octodns/cmds/sync.py", line 38, in main
    manager.sync(eligible_zones=args.zone, eligible_sources=args.source,
  File "/usr/local/lib/python3.8/site-packages/octodns/manager.py", line 369, in sync
    ps, d = future.result()
  File "/usr/local/lib/python3.8/site-packages/octodns/manager.py", line 57, in result
    return self.func(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.8/site-packages/octodns/manager.py", line 262, in _populate_and_plan
    plan = target.plan(zone)
  File "/usr/local/lib/python3.8/site-packages/octodns/provider/base.py", line 51, in plan
    exists = self.populate(existing, target=True, lenient=True)
  File "/usr/local/lib/python3.8/site-packages/octodns/provider/azuredns.py", line 378, in populate
    self._check_zone(zone_name)
  File "/usr/local/lib/python3.8/site-packages/octodns/provider/azuredns.py", line 327, in _check_zone
    self._dns_client.zones.get(self._resource_group, name)
  File "/usr/local/lib/python3.8/site-packages/azure/mgmt/dns/v2018_05_01/operations/_zones_operations.py", line 266, in get
    raise exp
msrestazure.azure_exceptions.CloudError: Azure Error: ResourceNotFound
Message: The Resource 'Microsoft.Network/dnszones/blahblah.com' under resource group 'dns' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix
```

Would expect this to detect that it doesn't exist and plan to create it.

**Comment by elliot-resdiary** [comment]
It looks like the Azure DNS provider tries to catch the 'resource not found' error when fetching the domain and then creates the domain if it finds that specific error.
https://github.com/octodns/octodns/blob/master/octodns/provider/azuredns.py#L330

However, the janky way it detects a 'resource not found' error is by comparing the human-readable error message returned by Azure with an expected error message. Since error messages aren't actually guaranteed to stay the same this was bound to be unreliable, and the actual error message returned by Azure is now appended with `For more details please go to https://aka.ms/ARMResourceNotFoundFix` which I'm thinking causes the check to fail.
