### ISSUE TITLE
ModuleNotFoundError: No module named 'fqdn' -- missing from setup.py

### ISSUE THREAD

**Issue by yzguy** [octodns/octodns#658]
Hit this error trying to get my environment set up again to work on another issue

```
-> octodns-sync --config-file=./config/production.yaml yzguy.io.
Traceback (most recent call last):
  File "/home/yzguy/Projects/octotest/venv/bin/octodns-sync", line 5, in <module>
    from octodns.cmds.sync import main
  File "/home/yzguy/Projects/octotest/venv/lib/python3.8/site-packages/octodns/cmds/sync.py", line 10, in <module>
    from octodns.manager import Manager
  File "/home/yzguy/Projects/octotest/venv/lib/python3.8/site-packages/octodns/manager.py", line 14, in <module>
    from .provider.base import BaseProvider
  File "/home/yzguy/Projects/octotest/venv/lib/python3.8/site-packages/octodns/provider/base.py", line 11, in <module>
    from ..zone import Zone
  File "/home/yzguy/Projects/octotest/venv/lib/python3.8/site-packages/octodns/zone.py", line 14, in <module>
    from .record import Create, Delete
  File "/home/yzguy/Projects/octotest/venv/lib/python3.8/site-packages/octodns/record/__init__.py", line 13, in <module>
    from fqdn import FQDN
ModuleNotFoundError: No module named 'fqdn'
```

Looks like this just something missed in #631, introduced on this [line](https://github.com/octodns/octodns/blob/master/octodns/record/__init__.py#L13)

Needs to be added to setup.py

**Comment by ross** [comment]
Doh. My bad for not thinking of this when I reviewed https://github.com/octodns/octodns/pull/631

**Comment by yzguy** [comment]
Have no fear, a PR is here! #659
