### ISSUE TITLE
Unable to convert CNAME record to A record on Cloudflare

### ISSUE THREAD

**Issue by deric** [octodns/octodns#666]
I'm unable to change `CNAME` record to `A`.
```
* cloudflare (CloudflareProvider)
*   Create <ARecord A 3600, foo.example.com., ['1.1.1.1']> (yaml_example)
*   Delete <CnameRecord CNAME 3600, foo.example.com., bar01.example.net.>
*   Summary: Creates=1, Updates=0, Deletes=1, Existing Records=42
********************************************************************************


2021-01-28T17:26:04  [140277747840832] INFO  CloudflareProvider[cloudflare] apply: making changes
Traceback (most recent call last):
  File "./venv/bin/octodns-sync", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.8/site-packages/octodns/cmds/sync.py", line 38, in main
    manager.sync(eligible_zones=args.zone, eligible_targets=args.target,
  File "/usr/lib/python3.8/site-packages/octodns/manager.py", line 344, in sync
    total_changes += target.apply(plan)
  File "/usr/lib/python3.8/site-packages/octodns/provider/base.py", line 95, in apply
    self._apply(plan)
  File "/usr/lib/python3.8/site-packages/octodns/provider/cloudflare.py", line 576, in _apply
    getattr(self, '_apply_{}'.format(class_name))(change)
  File "/usr/lib/python3.8/site-packages/octodns/provider/cloudflare.py", line 433, in _apply_Create
    self._request('POST', path, data=content)
  File "/usr/lib/python3.8/site-packages/octodns/provider/cloudflare.py", line 101, in _request
    raise CloudflareError(resp.json())
octodns.provider.cloudflare.CloudflareError: A CNAME record with that host already exists.
```
Similar issue #507 but for Route53 provider.

**Comment by deric** [comment]
I guess the problem is [here](https://github.com/octodns/octodns/blob/master/octodns/provider/cloudflare.py#L534):

>         # To do this as safely as possible we'll add new things first, update
>         # existing things, and then remove old things. This should (try) and
>         # ensure that we have as many value CF records in their system as
>         # possible at any given time. Ideally we'd have a "batch" API that
>         # would allow create, delete, and upsert style stuff so operations
>         # could be done atomically, but that's not available so we made the
>         # best of it...
> 
>         # However, there are record types like CNAME that can only have a
>         # single value. B/c of that our create and then delete approach isn't
>         # actually viable. To address this we'll convert as many creates &
>         # deletes as we can to updates. This will have a minor upside of
>         # resulting in fewer ops and in the case of things like CNAME where
>         # there's a single create and delete result in a single update instead.

The idea seems to be nice, but doesn't work in this case. The change was introduced in #277. The plan should either apply delete first:

```
* cloudflare (CloudflareProvider)
*   Delete <CnameRecord CNAME 3600, foo.example.com., bar01.example.net.>
*   Create <ARecord A 3600, foo.example.com., ['1.1.1.1']> (yaml_example)
```
or convert it into update, which doesn't happen here.

**Comment by yzguy** [comment]
#656 is the issue where this is tracked. It basically comes down to A records are processed before CNAMEs, which is why it tries to create the A record before deleting the CNAME.
