### ISSUE TITLE
Unknown provider class: octodns_route53.Route53Provider error

### ISSUE THREAD

**Issue by dogsbody-awab** [octodns/octodns#862]
Hi, 

I'm testing the syncing of a zone in dnsmadeeasy to route53 via `octodns-sync --config-file=./config/config.yaml` however I am running into the error below each time I do a dry run:
![image](https://user-images.githubusercontent.com/94059589/150787279-f9988a96-25fa-4422-848f-453f04d0154c.png)

I believe I have set the correct class in the config file as seen below:
![image](https://user-images.githubusercontent.com/94059589/150787750-0bb1441b-4bca-4467-a983-230e61bdd067.png)
![image](https://user-images.githubusercontent.com/94059589/150787848-da949cdb-09d8-4987-9bc9-5f91f3292d79.png)

I have also run `pip install octodns_route53` and am running the versions below:
Python==3.8.10
octodns==0.9.14
octodns_route53==0.0.2

I was getting the same error when trying to sync with digitalocean too but the class for DnsMadeEasy (octodns_dnsmadeeasy.DnsMadeEasyProvider) works without any problem.

Any help please?

**Comment by ross** [comment]
I just recreated a minimal setup of that and the exception before the one screenshotted above is the key to what's going wrong. Python is failing to import `octodns_route53.Route53Provider` b/c `boto3` is not installed.

```
(env) coho:foo ross$ octodns-sync --config-file=config/dev.yaml
2022-01-24T07:03:56  [4621905408] INFO  Manager __init__: config_file=config/dev.yaml
2022-01-24T07:03:56  [4621905408] INFO  Manager __init__:   max_workers=1
2022-01-24T07:03:56  [4621905408] INFO  Manager __init__:   include_meta=False
2022-01-24T07:03:56  [4621905408] ERROR Manager _get_{}_class: Unable to import module octodns_route53.Route53Provider
Traceback (most recent call last):
  File "/private/tmp/foo/env/lib/python3.9/site-packages/octodns/manager.py", line 190, in _get_named_class
    module = import_module(module_name)
  File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/private/tmp/foo/env/lib/python3.9/site-packages/octodns_route53/__init__.py", line 5, in <module>
    from boto3 import client
ModuleNotFoundError: No module named 'boto3'
Traceback (most recent call last):
  File "/private/tmp/foo/env/lib/python3.9/site-packages/octodns/manager.py", line 190, in _get_named_class
    module = import_module(module_name)
  File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/private/tmp/foo/env/lib/python3.9/site-packages/octodns_route53/__init__.py", line 5, in <module>
    from boto3 import client
ModuleNotFoundError: No module named 'boto3'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/private/tmp/foo/env/bin/octodns-sync", line 8, in <module>
    sys.exit(main())
  File "/private/tmp/foo/env/lib/python3.9/site-packages/octodns/cmds/sync.py", line 37, in main
    manager = Manager(args.config_file)
  File "/private/tmp/foo/env/lib/python3.9/site-packages/octodns/manager.py", line 115, in __init__
    _class = self._get_named_class('provider', _class)
  File "/private/tmp/foo/env/lib/python3.9/site-packages/octodns/manager.py", line 194, in _get_named_class
    raise ManagerException(f'Unknown {_type} class: {_class}')
octodns.manager.ManagerException: Unknown provider class: octodns_route53.Route53Provider
```

This problem was addressed in https://github.com/octodns/octodns-route53/pull/6 and as soon as https://github.com/octodns/octodns-route53/pull/8 is merged and a release built it will be available in pypy as 0.0.3.

In the meantime you can work around it with `pip install boto3`

Will look into digital ocean in a bit.

**Comment by ross** [comment]
DigitalOceanProvider seems to work for me:

```console
$ python3 -m venv env
$ source env/bin/activate
(env) $ pip install octodns octodns-digitalocean
```

```yaml
providers:

  config:
    class: octodns.provider.yaml.YamlProvider
    directory: ./config

  digitalocean:
    class: octodns_digitalocean.DigitalOceanProvider
    # i don't have creds for it, but that shouldn't be required to see if we can import it

zones:
  exxampled.com.:
    sources:
      - config
    targets:
      - digitalocean
```

This is expected to fail, but note it's not failing to import DigitalOceanProvider:

```console
(env) $ octodns-sync --config-file=config/dev.yaml
2022-01-24T07:23:09  [4496752128] INFO  Manager __init__: config_file=config/dev.yaml
2022-01-24T07:23:09  [4496752128] INFO  Manager __init__:   max_workers=1
2022-01-24T07:23:09  [4496752128] INFO  Manager __init__:   include_meta=False
2022-01-24T07:23:09  [4496752128] ERROR Manager Invalid provider config
Traceback (most recent call last):
  File "/private/tmp/foo/env/lib/python3.9/site-packages/octodns/manager.py", line 118, in __init__
    self.providers[provider_name] = _class(provider_name, **kwargs)
TypeError: __init__() missing 1 required positional argument: 'token'
Traceback (most recent call last):
  File "/private/tmp/foo/env/lib/python3.9/site-packages/octodns/manager.py", line 118, in __init__
    self.providers[provider_name] = _class(provider_name, **kwargs)
TypeError: __init__() missing 1 required positional argument: 'token'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/private/tmp/foo/env/bin/octodns-sync", line 8, in <module>
    sys.exit(main())
  File "/private/tmp/foo/env/lib/python3.9/site-packages/octodns/cmds/sync.py", line 37, in main
    manager = Manager(args.config_file)
  File "/private/tmp/foo/env/lib/python3.9/site-packages/octodns/manager.py", line 121, in __init__
    raise ManagerException('Incorrect provider config for ' +
octodns.manager.ManagerException: Incorrect provider config for digitalocean
```

**Comment by dogsbody-awab** [comment]
Thank you, the sync with route53 works now. I believe digitalocean wasn't working as I initially ran `pip install octodns_digitalocean` but after installing `octodns-digitalocean` with the dash, it seems to work. I believe the https://github.com/octodns/octodns-digitalocean/ page needs to be updated, as it states to install it with a underscore instead of a dash.
