### ISSUE TITLE
Record processing order

### ISSUE THREAD

**Issue by orient19** [octodns/octodns#904]
Hello! I think you first need to delete records, and then create them so that there is no such conflict (look at the log).

```
octodns-sync --version
octoDNS 0.9.17
```

log:
```
********************************************************************************
* mydomain.ru.
********************************************************************************
* edgecenter (GCoreProvider)
*   Delete <CnameRecord CNAME 600, auth.mydomain.ru., fe-synterra-https2.mydomain.ru.>
*   Create <ARecord A 600, auth.mydomain.ru., ['xxx.xxx.xxx.xxx']> (config)
*   Summary: Creates=1, Updates=0, Deletes=1, Existing Records=617
********************************************************************************


2022-05-26T10:49:12  [140690960328512] INFO  GCoreProvider[edgecenter] apply: making 2 changes to mydomain.ru.
2022-05-26T10:49:12  [140690960328512] INFO  GCoreProvider[edgecenter] creating: Create <ARecord A 600, auth.mydomain.ru., ['xxx.xxx.xxx.xxx']> (config)
Traceback (most recent call last):
  File "/usr/local/bin/octodns-sync", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/octodns/cmds/sync.py", line 38, in main
    manager.sync(eligible_zones=args.zone, eligible_sources=args.source,
  File "/usr/local/lib/python3.8/dist-packages/octodns/manager.py", line 523, in sync
    total_changes += target.apply(plan)
  File "/usr/local/lib/python3.8/dist-packages/octodns/provider/base.py", line 226, in apply
    self._apply(plan)
  File "/usr/local/lib/python3.8/dist-packages/octodns_gcore/__init__.py", line 594, in _apply
    getattr(self, f"_apply_{class_name.lower()}")(change)
  File "/usr/local/lib/python3.8/dist-packages/octodns_gcore/__init__.py", line 556, in _apply_create
    self._client.record_create(
  File "/usr/local/lib/python3.8/dist-packages/octodns_gcore/__init__.py", line 111, in record_create
    self._request(
  File "/usr/local/lib/python3.8/dist-packages/octodns_gcore/__init__.py", line 88, in _request
    r.raise_for_status()
  File "/usr/local/lib/python3.8/dist-packages/requests/models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: https://dnsapi.gcorelabs.com/v2/zones/mydomain.ru/auth.mydomain.ru./A
```

**Comment by ross** [comment]
Well it didn't take much digging:

https://github.com/octodns/octodns-gcore/blob/0777ecd51e07148d522ea9aa34725fc8161ada6c/octodns_gcore/__init__.py#L590

```python
        changes.reverse()

        for change in changes:
            class_name = change.__class__.__name__
            getattr(self, f"_apply_{class_name.lower()}")(change)
```

Unfortunately there's no comment about why the reverse is there so I think the best bet is to remove it. 

Moving this issue into that repo.
