### ISSUE TITLE
Applying zone containing a Policy Record crashes with `KeyError: 'TTL'`

### ISSUE THREAD

**Issue by Typositoire** [octodns/octodns#990]
Regarding [this](https://github.com/octodns/octodns/issues/232), the conclusion was that OctoDNS should skip offending records and we agree but that was never done. When a Route53 has a record configured as a Policy Record, we can't do anything it just error out. Being able to ignore those would be nice!

We tried with this but I guess filters are applied later

```
processors:
  not-these:
    class: octodns.processor.filter.NameRejectlistFilter
    rejectlist:
      - meuhmeuh
```

```
Traceback (most recent call last):
  File "/home/ydavid/.local/bin/octodns-sync", line 8, in <module>
    sys.exit(main())
  File "/home/ydavid/.local/lib/python3.10/site-packages/octodns/cmds/sync.py", line 57, in main
    manager.sync(
  File "/home/ydavid/.local/lib/python3.10/site-packages/octodns/manager.py", line 592, in sync
    ps, d = future.result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 458, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/ydavid/.local/lib/python3.10/site-packages/octodns/manager.py", line 435, in _populate_and_plan
    plan = target.plan(zone, processors=processors)
  File "/home/ydavid/.local/lib/python3.10/site-packages/octodns/provider/base.py", line 178, in plan
    exists = self.populate(existing, target=True, lenient=True)
  File "/home/ydavid/.local/lib/python3.10/site-packages/octodns_route53/__init__.py", line 1240, in populate
    data = getattr(self, f'_data_for_{record_type}')(rrset)
  File "/home/ydavid/.local/lib/python3.10/site-packages/octodns_route53/__init__.py", line 914, in _data_for_geo
    'ttl': int(rrset['TTL']),
KeyError: 'TTL'
```

**Comment by Typositoire** [comment]
We have a temporary fix that is far from "clean" but at least it gives you an idea of what we need:

https://github.com/Typositoire/octodns-route53/pull/1/files

**Comment by ross** [comment]
> We have a temporary fix that is far from "clean" but at least it gives you an idea of what we need:
> 
> https://github.com/Typositoire/octodns-route53/pull/1/files

That's roughly what I was thinking in https://github.com/octodns/octodns/issues/232#issuecomment-381746104. 

The main suggestion I'd have on the changes would be to move the check up above the [call to `_data_for_*`](https://github.com/Typositoire/octodns-route53/pull/1/files#diff-5906dd5e4b6c53e7ef5a9ad465e17b6b16580eac699d8c4a44b70c26815b84a5R1226) and move the check you have in `_data_for_geo` there tweaked to something like

```python
if 'TrafficPolicyInstanceId' in rrset:
    self.log.warning('TrafficPolicies are not supported, skipping %s', rrset['Name'])
    continue
```

If you want to PR that we can go from there.

**Comment by bencaron** [comment]
Hi @ross : I reworked @Typositoire fix on top of `octodns-route53` main branch.

Hoping this can be merged as-is now.

**Comment by ross** [comment]
Closed by https://github.com/octodns/octodns-route53/pull/65
